'use client';

import jsPDF from 'jspdf';

export interface VoicePlanData {
  transcript: string;
  summary: string;
  keyPoints: string[];
  recommendations?: string[];
  duration?: string;
  planTitle?: string;
  nextSteps?: string;
}

export function generateVoicePlanPDF(data: VoicePlanData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - (margin * 2);
  let yPos = margin;

  // Helper function to add text with word wrap
  const addText = (
    text: string,
    fontSize: number,
    isBold: boolean = false,
    color: [number, number, number] = [0, 0, 0]
  ) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    doc.setTextColor(color[0], color[1], color[2]);

    const lines = doc.splitTextToSize(text, maxWidth);
    lines.forEach((line: string) => {
      if (yPos > pageHeight - margin - 10) {
        doc.addPage();
        yPos = margin;
      }
      doc.text(line, margin, yPos);
      yPos += fontSize * 0.5;
    });
    yPos += 5;
  };

  // Header
  doc.setFillColor(220, 38, 38); // Boxing red
  doc.rect(0, 0, pageWidth, 45, 'F');

  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('THE BOXING LOCKER', pageWidth / 2, 15, { align: 'center' });

  doc.setFontSize(16);
  const title = data.planTitle || 'Voice Coaching Session Plan';
  doc.text(title, pageWidth / 2, 28, { align: 'center' });

  doc.setFontSize(10);
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, 40, { align: 'center' });

  yPos = 55;

  // Session Summary
  addText('SESSION SUMMARY', 16, true, [220, 38, 38]);
  doc.setDrawColor(220, 38, 38);
  doc.line(margin, yPos - 2, pageWidth - margin, yPos - 2);
  yPos += 5;

  if (data.duration) {
    addText(`Duration: ${data.duration}`, 12);
  }
  yPos += 5;

  // Key Points
  if (data.keyPoints && data.keyPoints.length > 0) {
    addText('KEY COACHING POINTS', 16, true, [220, 38, 38]);
    doc.line(margin, yPos - 2, pageWidth - margin, yPos - 2);
    yPos += 5;

    data.keyPoints.forEach((point, index) => {
      addText(`${index + 1}. ${point}`, 11);
    });
    yPos += 5;
  }

  // Summary
  addText('COACHING SUMMARY', 16, true, [220, 38, 38]);
  doc.line(margin, yPos - 2, pageWidth - margin, yPos - 2);
  yPos += 5;

  const cleanSummary = data.summary
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/#{1,6}\s/g, '')
    .replace(/```[\s\S]*?```/g, '')
    .replace(/`(.*?)`/g, '$1');

  addText(cleanSummary, 11);
  yPos += 5;

  // Next Steps (from AI tool call)
  if (data.nextSteps) {
    if (yPos > pageHeight - margin - 30) {
      doc.addPage();
      yPos = margin;
    }
    addText('YOUR NEXT STEPS', 16, true, [220, 38, 38]);
    doc.line(margin, yPos - 2, pageWidth - margin, yPos - 2);
    yPos += 5;

    addText(data.nextSteps, 11);
    yPos += 5;
  }

  // Recommendations
  if (data.recommendations && data.recommendations.length > 0) {
    if (yPos > pageHeight - margin - 30) {
      doc.addPage();
      yPos = margin;
    }
    addText('RECOMMENDATIONS', 16, true, [220, 38, 38]);
    doc.line(margin, yPos - 2, pageWidth - margin, yPos - 2);
    yPos += 5;

    data.recommendations.forEach((rec, index) => {
      addText(`${index + 1}. ${rec}`, 11);
    });
    yPos += 5;
  }

  // Full Transcript (if space allows)
  if (yPos < pageHeight - margin - 50 && data.transcript) {
    if (yPos > pageHeight - margin - 100) {
      doc.addPage();
      yPos = margin;
    }
    addText('FULL TRANSCRIPT', 16, true, [220, 38, 38]);
    doc.line(margin, yPos - 2, pageWidth - margin, yPos - 2);
    yPos += 5;

    const cleanTranscript = data.transcript
      .replace(/\*\*(.*?)\*\*/g, '$1')
      .replace(/\*(.*?)\*/g, '$1')
      .replace(/#{1,6}\s/g, '')
      .replace(/```[\s\S]*?```/g, '')
      .replace(/`(.*?)`/g, '$1');

    // Truncate if too long
    const maxTranscriptLength = 2000;
    const transcriptToShow = cleanTranscript.length > maxTranscriptLength
      ? cleanTranscript.substring(0, maxTranscriptLength) + '...'
      : cleanTranscript;

    addText(transcriptToShow, 9, false, [100, 100, 100]);
  }

  // Footer
  const footerY = pageHeight - 20;
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by The Boxing Locker', pageWidth / 2, footerY, { align: 'center' });
  doc.text('Visit: www.tbltrainingplans.com', pageWidth / 2, footerY + 8, { align: 'center' });

  // Save PDF
  doc.save(`voice-coaching-plan-${new Date().toISOString().split('T')[0]}.pdf`);
}

